# ... 
- PRIVATE_KEY: ${{ secrets.SSH_SOLID_KEY }} # Reference the private key stored in GitHub Secrets
+ PRIVATE_KEY: ${{ secrets.YOUR_GITHUB_REPOSITORY_SECRET_NAME }} # Reference the private key stored in GitHub Secrets

# ...     
 
+          ssh -o StrictHostKeyChecking=no -i private_key.pem -tt yourusername@yourexternalip <<EOF  
    

            cd your-repo-directory-name #go to repo
